### ISSUE TITLE
기능 구현 Proposal

### ISSUE THREAD

**Issue by bongjunj** [2489D/Normio#5]
아키텍처는 모두 완성 되었으니
확장 가능하게 잘 설계된 아키텍처를 잘 활용해 빠르게 기능을 추가 해봅시다.

# 개요

| 기능 | 우선도 | 구현 난이도 | 구현 여부 |
|-|-|-|-|
| 타이머 | 매우 높음 | 쉬움 | Yes |
| 유저 인증 | 낮음 | 보통~어려움 | Don't |
| 제출물 관리 | 매우 높음 | 보통~어려움 | Yes |
| 비디오 챗 | 높음 | 어려움 | On Progress |
| 시험 로그 관리 | 보통 | 매우 쉬움 | No |

## Timer 기능

* 구현해야함
* Timer 인스턴스 구현 방법 결정하기
* 이후 구현은 어렵지 않을 것으로 보임

## User Authenticatoin and Authorisation , User Permission Control

* 구현할 것 인가? (부수적인 기능임)
* 구현하지 않더라도, 구현이 가능하게 구현 가능성을 어떻게 소스 코드에 표현할 것인가?
* 유저 별 Permission 모델링 시도는 하기

## Submission System 구체화

* 구현해야 함(필수적인 기능)
* Submission의 종류 구체화
    - 설문 형식
    - 파일 형식 (이미지, pdf 등)
* Asp.net core + Giraffe 파일 전송

## P2P Video Chat 구현

* 구현하면 매우 좋음
* 참고 자료 :  https://github.com/Shhzdmrz/SignalRCoreWebRTC

## 시험 로그 관리

* 이벤트 스토어에 있는 거 뿌리면 됨

**Comment by SunghyunKimKAIST** [comment]
### Timer 동시성 문제
- 여러개의 Timer 함수가 동시에 불리면 Heap 저장소를 read하고 write하는 과정에서 버그가 발생하는 것으로 보임 (추측)
- 타이머 간격을 1분 이상으로 하면, millisec 단위에서 동시에 불리지만 않는다면 중대한 버그는 없을 것으로 생각됨
- 해결방법
    1. MailboxProcessor (구현하는데 하루 정도 예상)
    1. Lock (속도 저하 예상됨, 2시간 예상)
    1. 무시하고 그냥 진행
- 일단 무시하고 그냥 진행하겠음
- SetTimer를 제외한 다른 함수들은 테스트 필요

**Comment by bongjunj** [comment]
+ Message 기능

student -> host (ask)
host -> host
host -> everyone (notice)

**Comment by SeungminHwang** [comment]
Client features
* Host
* Client

개요
* Host
  1. 로그인 정보
    > 접속 ID, 감독자 이름
    > 시험 입장 시간
  2. 시험 정보
    > 기본 정보 : 시험 이름, 시험 시작 및 종료 시간
    > 접속자 수, 응시자 수 표시
  3. 관리 및 감독
    > 학생 출석 체크
    > 시험 기본 정보 변경 : 시작/종료 시간, 제출 횟수 제한, 늦은 입장 가능 여부
    > 시험 문제 공유 기능
    > 시험 제출 현황 체크
    > 학생들의 웹캠 화면 그리드로 보여주기
    > 질문 리스트 -> 각각의 질문에 응답 버튼 마련(for private reply)
    > 중요 공지 (전체 학생)

* Student
  1. 로그인 정보
    > 접속 ID, 학생 이름
    > 시험 입장 시간
  2. 시험 정보
    > 기본 정보 : 시험 이름, 시험 시작 및 종료 시간, 남은 시간
  3. 응시
    > 감독자 웹캠 영상
    > 시험 문제 열람 / 다운로드
    > 파일 제출
    > 파일 제출 완료 후 자율적으로 퇴실할 수 있게 함
    > 질문 : 본인 -> 조교



공통 구현 리스트
* 개인정보, 시험 정보 표시
* 질문, 공지용 채팅창 구현
* 웹캠 영상 전송?

학생 구현 리스트
* 출석 체크 기능 구현(체크박스?)
* 시험 퇴실 버튼 (미제출 시 퇴실 불가능)
* 시험 문제 열람(혹은 다운로드) 기능

호스트 구현 리스트
* 자동 출석 체크 기능 구현 (예 : 23/30 출석; 안 온 사람 리스트, 온 사람 리스트)
* 자동 제출 여부 체크 기능 구현 (예 : 15/30 제출; 미제출자 리스트, 제출자 리스트, 파일 조회)
* 시험 기본 정보 관리 기능 구현 (시험 시작/종료 시간 수정, 복수 제출 허용 등)
* 시험 파일 공유 기능 구현
* 채팅창에 학생 개별 답장 기능 구현


구현하면서 고민해야 할 점
* 화상 회의 시스템에 비해 특별히 더 좋은 기능? => 강조 필요함

**Comment by bongjunj** [comment]
https://medium.com/@eulerfx/f-async-guide-eb3c8a2d180a
